common: &common
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV["MAX_THREADS"] || 5 %>

development:
  <<: *common

test:
  <<: *common

production:
  <<: *common
